kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-monitoring-kube-prometheus-prometheus-db
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/repo/storage-monitoring/prometheus-db/"
